### ISSUE TITLE
Python: Automate releases

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/tag-expressions#20]
We've adopted a release process based on GitHub Actions - documented in [RELEASING.md](https://github.com/cucumber/.github/blob/main/RELEASING.md)

In order to automate Python releases, we need a new `.github/workflows/release-pypi.yml`

**Comment by jenisys** [comment]
@aslakhellesoy @mpkorstanje 
FYI: I will look into this in the next few days.

**Comment by ehuelsmann** [comment]
https://github.com/cucumber/action-publish-pypi exists and can be integrated..

**Comment by luke-hill** [comment]
@jenisys - Hi there. Before we look into this can we ensure the other repos that have automated python releases on (such as cucumber-expressions), are updated / stable. I tried to recently release cucumber-expressions which broke for python.

**Comment by luke-hill** [comment]
Last release was here: https://pypi.org/project/cucumber-tag-expressions/ (For my benefit there are 2 conflicting versions of this package).
