### ISSUE TITLE
Perl: Automate releases

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/tag-expressions#21]
We've adopted a release process based on GitHub Actions - documented in [RELEASING.md](https://github.com/cucumber/.github/blob/main/RELEASING.md)

In order to automate Perl releases, we need a new `.github/workflows/release-cpan.yml`

**Comment by mattwynne** [comment]
I've started work on https://github.com/cucumber/action-publish-cpan

**Comment by ehuelsmann** [comment]
@mattwynne, @aslakhellesoy, there are Perl releases from Cucumber-Messages and Gherkin. What's missing here that Tag-Expressions isn't releasing? (I was under the impression that in the past work on GitHub release actions was restricted to a few people to prevent security attacks on our community. Is that still the case?)

**Comment by mpkorstanje** [comment]
Currently messages and tag expressions are not released for Perl either.

**Comment by ehuelsmann** [comment]
Ok. But if editing the release actions is restricted to a very small group of people, then: am I part of that group?

**Comment by ehuelsmann** [comment]
@mattwynne there's a "release/v1.0.0" tag in the repository you pointed to.

Is it safe to say that all that remains to be done is build this into the release flows of Cucumber-Messages and Cucumber-TagExpressions?

**Comment by mpkorstanje** [comment]
You're in the group of people documented in:

https://github.com/cucumber/.github/blob/main/RELEASING.md

**Comment by mpkorstanje** [comment]
Don't think you'll get an answer from Matt quickly. He's mostly busy with other stuff at the moment. You may have to check his homework so to say.

**Comment by mattwynne** [comment]
Hi all,

I'm rusty with this infrastructure, but the obvious thing that's missing is a `.github/workflows/release-cpan.yml` similar to [this one](https://github.com/cucumber/gherkin/blob/main/.github/workflows/release-cpan.yaml).

We'll also need the two secrets used in that workflow to be added to this repo's GitHub settings. I think those are to be found in Keybase.

@ehuelsmann if you notice anything that could be better documented about all this, please either say so (and I'll try to write things up) or add it yourself if you have time.

**Comment by mattwynne** [comment]
Right now I'm not sure I can access keybase as I've lost access to my `cucumber.io` email account.

**Comment by ehuelsmann** [comment]
@mpkorstanje  A few hours is definitely soon enough. Thanks!

**Comment by ehuelsmann** [comment]
Thanks!
